Compound file updated to V11 and evaluation plan
Open-Systems-Pharmacology/Metformin-Model pull request #3
Opened 2024-11-15 21:02 UTC by mgsc1020

please review @PavelBal

2024-12-23 14:07 UTC, Yuri05 commented
Please rename **Metformin-Model V11.json** to **Metformin-Model.json**

2024-12-23 14:27 UTC, Yuri05 commented
Missing observed data mappings in some simulations under **metformin model verification po**
![grafik](https://github.com/user-attachments/assets/9d6134f5-5f15-4eff-b127-f6708c25aeb4)

2024-12-23 14:37 UTC, Yuri05 commented
some cross references in report seem to be invalid:
![grafik](https://github.com/user-attachments/assets/4e56a711-8fdf-41df-a1cb-51ea080a59c0)

2024-12-23 14:43 UTC, Yuri05 commented
Author name seems to be used inconsistently: _Morissey_ vs. _Morrisey_ vs. _Morrissey_

2025-01-03 11:42 UTC, mgsc1020 commented
@Yuri05 thank you for your comments. I addressed the author names and data mappings. 
For the comment on the cross-references to report sections #221, #222, and #224 comment, can you give me a hint on how to solve this? I don't think I ran into this error when I ran the report, and I'm unsure how to track it from my side.

2025-01-03 13:26 UTC, Yuri05 commented
> For the comment on the cross-references to report sections #221, #222, and #224 comment, can you give me a hint on how to solve this? I don't think I ran into this error when I ran the report, and I'm unsure how to track it from my side.

For those chapters no header numbers were created (e.g. compare https://github.com/Yuri05/Metformin-Model/blob/review/Evaluation/report/report.md#in-vitro-and-physicochemical-data).

So you have 3 alternative options for fixing:
1. Adjust the references (e.g. use `#in-vitro-and-physicochemical-data` instead of `#221-in-vitro-and-physicochemical-data`)
2. Add subchapter numbers to your static content (would not do this).
3. [**Best option**] Create **your own anchors** as described under https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/qualification-workflow.html#referencing
  * For subchapters which are referenced elsewhere, add `<a id="chapter-reference-id"></a>` directly above or directly after the chapter header in the markdown file. Use only lower case letters, "-" and digits, e.g.
  
`### In vitro and physicochemical data<a id="in-vitro-data"></a>`

  * Then you can always reference the chapter by its anchor as `[s. tralala](#in-vitro-data)`
  This is the safest way as it does not rely on the chapter number, chapter title or the way how the GitHub referencing replaces the special characters in automatically created anchors.

2025-01-23 10:29 UTC, PavelBal requested changes

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The parameter value for `Specific intestinal permeability` and were optimized based on clinical oral data, see [Section 2.3.4](#model-parameters-and-assumptions-identification). The saturable
Something is missing here - "and were" does not sound right.

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +No information regarding active transport processes at the basolateral side of the intestinal mucosa could be obtained, therefore, the passive  basolateral permeability) `(P (intracellular -> interst
```suggestion
No information regarding active transport processes at the basolateral side of the intestinal mucosa could be obtained, therefore, the passive  basolateral permeability `(P (intracellular -> interstitial)` was optimized, see [Section 2.3.4](#model-parameters-and-assumptions-identification).
```

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The measured solubility in at pH 6.8 was used in the model (see [Section 2.2.1](#invitro-and-physico-chemical-data)).
The measured solubility in?

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +An important parameter influencing the resulting volume of distribution is lipophilicity. The reported experimental logP ranged from -1.43 was used in this model (see [Section 2.2.1](#in-vitro-and-ph
"The reported experimental logP ranged from" to?

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The transport protein involved in metformin PK were implemented in the model via Michaelis-Menten kinetics as described below:
```suggestion
The transport proteins involved in metformin PK were implemented in the model via Michaelis-Menten kinetics as described below: 
```

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The UGT1A9 expression profiles are based on high-sensitive real-time RT-PCR ([Nishimura 2005](#5-references)). Metabolic enzyme activity was described as saturable process following Michaelis-Menten
```suggestion
The UGT1A9 expression profiles are based on high-sensitive real-time RT-PCR ([Nishimura 2005](#5-references)). Metabolic enzyme activity was described as saturable process following Michaelis-Menten kinetics, where `Km` and `kcat` were optimized based on clinical data (see [Section 2.3.4](#model-parameters-and-assumptions-identification)).
```

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The OCT1 expression profiles are based on Microarray expression data ([Kolesnikov 2015](#5-references)). Transporter activity was described as saturable process following Michaelis-Menten kinetics, w
```suggestion
The OCT1 expression profiles are based on Microarray expression data ([Kolesnikov 2015](#5-references)). Transporter activity was described as saturable process following Michaelis-Menten kinetics, where the `Km` was taken from literature and `kcat` was optimized based on clinical data (see [Section 2.3.4](#model-parameters-and-assumptions-identification)).
```

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The OCT2 expression profiles are based on Expressed Sequece Tags (EST) ([NCBI 2019](#5-references)). Transporter activity was described as saturable process following Michaelis-Menten kinetics, were
```suggestion
The OCT2 expression profiles are based on Expressed Sequece Tags (EST) ([NCBI 2019](#5-references)). Transporter activity was described as saturable process following Michaelis-Menten kinetics, where the `Km` was taken from literature and `kcat` was optimized based on clinical data (see [Section 2.3.4](#model-parameters-and-assumptions-identification)).
```

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The MATE1 expression profiles assumed 100% expression in the Kidney ([Otsuka 2005](#5-references) and [Masuda 2006](#5-references)). Transporter activity was described as saturable process following
```suggestion
The MATE1 expression profiles assumed 100% expression in the Kidney ([Otsuka 2005](#5-references) and [Masuda 2006](#5-references)). Transporter activity was described as saturable process following Michaelis-Menten kinetics, where the `Km` was taken from literature and `kcat` was optimized based on clinical data (see [Section 2.3.4](#model-parameters-and-assumptions-identification)).
```

2025-01-23 10:29 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +The UGT1A9 expression profiles are based on high-sensitive real-time RT-PCR ([Nishimura 2005](#5-references)). Metabolic enzyme activity was described as saturable process following Michaelis-Menten
PMAT is Hill kinetics and not MM.

2025-03-24 16:31 UTC, PavelBal approved these changes

2025-03-24 16:32 UTC, PavelBal commented
@Yuri05 I approve..

2025-04-07 09:18 UTC, merged